### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by oscardelgado** [RicardoRB/isfirebasetestlabactivated#1]
Thanks for this package.
Could you please migrate it to Null Safety?

**Comment by RicardoRB** [comment]
Hi @oscardelgado

For sure, give me a moment, and I'll do it soon as possible

**Comment by RicardoRB** [comment]
Hi again @oscardelgado 

I just published the version 2.0.0. Please let me know if everything is working fine!

**Comment by oscardelgado** [comment]
Perfect! Thanks
