### ISSUE TITLE
Incompatible with AGP 8

### ISSUE THREAD

**Issue by ciriousjoker** [RicardoRB/isfirebasetestlabactivated#3]
Needs a namespace declaration, which has now become mandatory instead of optional.

**Comment by mortenthansen** [comment]
@RicardoRB Can we get this PR merged?

I am hoping it will solve my:
/my_app/build/is_firebase_test_lab_activated/intermediates/merged_res/profile/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

on flutter 3.24.1

**Comment by RicardoRB** [comment]
Oh sure, I don't know why I didn't see this before, I'm going to merge it and create a new version
